// AUTO-DERIVED from docs/CX-taxonomy-products-equipment.md (signed off 07/16/2026).
// The CX Marketplace Product/Material + Equipment taxonomy: two independent trees,
// two levels deep (Category -> Sub-category), stable slugs that never change even if
// a label does. A listing is Trade + EITHER one Product OR one Equipment category
// (mutually exclusive; see ItemKind), each with an optional sub-category. This module
// is framework-agnostic (no next/*), so the future mobile API reuses it verbatim.

export type ItemKind = "product" | "equipment";

export type TaxSubcategory = { slug: string; label: string };
export type TaxCategory = {
  slug: string;
  label: string;
  /** CSI MasterFormat division anchor (products only). */
  masterFormat?: string;
  subcategories: TaxSubcategory[];
};

export const PRODUCT_CATEGORIES: TaxCategory[] = [
  { slug: "lumber-composites", label: "Lumber & Composites", masterFormat: "Div 06", subcategories: [{ slug: "dimensional-lumber", label: "Dimensional lumber" }, { slug: "studs", label: "Studs" }, { slug: "timbers-posts", label: "Timbers & posts" }, { slug: "pressure-treated-lumber", label: "Pressure-treated lumber" }, { slug: "engineered-lumber", label: "Engineered lumber (LVL, LSL, glulam)" }, { slug: "i-joists-trusses", label: "I-joists & trusses" }, { slug: "plywood", label: "Plywood" }, { slug: "osb-sheathing", label: "OSB & sheathing" }, { slug: "wood-decking", label: "Wood decking" }, { slug: "composite-pvc-decking", label: "Composite & PVC decking" }, { slug: "trim-moulding", label: "Trim & moulding" }] },
  { slug: "concrete-cement-masonry", label: "Concrete, Cement & Masonry", masterFormat: "Div 03, 04", subcategories: [{ slug: "ready-mix-concrete", label: "Ready-mix concrete" }, { slug: "bagged-concrete-cement", label: "Bagged concrete & cement" }, { slug: "mortar-grout", label: "Mortar & grout" }, { slug: "rebar-wire-mesh", label: "Rebar & wire mesh" }, { slug: "concrete-block-cmu", label: "Concrete block (CMU)" }, { slug: "brick", label: "Brick" }, { slug: "pavers", label: "Pavers" }, { slug: "retaining-wall-block", label: "Retaining wall block" }, { slug: "natural-manufactured-stone", label: "Natural & manufactured stone" }, { slug: "admixtures", label: "Admixtures" }, { slug: "forms-accessories", label: "Forms & form accessories" }, { slug: "sealers-curing-compounds", label: "Sealers & curing compounds" }] },
  { slug: "drywall-interior-finishes", label: "Drywall & Interior Finishes", masterFormat: "Div 09", subcategories: [{ slug: "drywall-panels", label: "Drywall panels" }, { slug: "backer-board", label: "Cement & tile backer board" }, { slug: "joint-compound-tape", label: "Joint compound & tape" }, { slug: "corner-bead", label: "Corner bead" }, { slug: "metal-studs-track", label: "Metal studs & track" }, { slug: "plaster-stucco", label: "Plaster & stucco" }, { slug: "ceiling-tile-grid", label: "Ceiling tile & grid" }, { slug: "acoustic-panels", label: "Acoustic panels" }] },
  { slug: "paint-coatings-sundries", label: "Paint, Coatings & Sundries", masterFormat: "Div 09 90 00", subcategories: [{ slug: "interior-paint", label: "Interior paint" }, { slug: "exterior-paint", label: "Exterior paint" }, { slug: "primers-sealers", label: "Primers & sealers" }, { slug: "stains-wood-finishes", label: "Stains & wood finishes" }, { slug: "industrial-protective-coatings", label: "Industrial & protective coatings" }, { slug: "caulk-sealants", label: "Caulk & sealants" }, { slug: "adhesives", label: "Adhesives" }, { slug: "brushes-rollers-sprayers", label: "Brushes, rollers & sprayer supplies" }, { slug: "tape-masking", label: "Tape & masking" }, { slug: "drop-cloths", label: "Drop cloths" }] },
  { slug: "roofing-siding", label: "Roofing & Siding", masterFormat: "Div 07", subcategories: [{ slug: "asphalt-shingles", label: "Asphalt shingles" }, { slug: "metal-roofing", label: "Metal roofing" }, { slug: "tile-slate-roofing", label: "Tile & slate roofing" }, { slug: "low-slope-membrane", label: "Low-slope membrane (TPO, EPDM, mod-bit)" }, { slug: "roofing-underlayment", label: "Underlayment" }, { slug: "flashing-drip-edge", label: "Flashing & drip edge" }, { slug: "gutters-downspouts", label: "Gutters & downspouts" }, { slug: "soffit-fascia", label: "Soffit & fascia" }, { slug: "vinyl-siding", label: "Vinyl siding" }, { slug: "fiber-cement-siding", label: "Fiber cement siding" }, { slug: "wood-engineered-siding", label: "Wood & engineered siding" }, { slug: "stone-veneer", label: "Stone veneer" }] },
  { slug: "insulation-weatherproofing", label: "Insulation & Weatherproofing", masterFormat: "Div 07", subcategories: [{ slug: "batt-insulation", label: "Batt insulation" }, { slug: "blown-in-loose-fill", label: "Blown-in & loose fill" }, { slug: "rigid-foam-board", label: "Rigid foam board" }, { slug: "spray-foam", label: "Spray foam" }, { slug: "mineral-wool", label: "Mineral wool" }, { slug: "radiant-barrier", label: "Radiant barrier" }, { slug: "house-wrap-air-barrier", label: "House wrap & air barrier" }, { slug: "vapor-barrier", label: "Vapor barrier" }, { slug: "waterproofing-membranes", label: "Waterproofing membranes" }, { slug: "weatherstripping", label: "Weatherstripping" }] },
  { slug: "doors-windows-millwork", label: "Doors, Windows & Millwork", masterFormat: "Div 08", subcategories: [{ slug: "interior-doors", label: "Interior doors" }, { slug: "exterior-doors", label: "Exterior doors" }, { slug: "garage-doors", label: "Garage doors" }, { slug: "hollow-metal-doors", label: "Hollow metal & commercial doors" }, { slug: "windows", label: "Windows" }, { slug: "skylights", label: "Skylights" }, { slug: "door-hardware-locksets", label: "Door hardware & locksets" }, { slug: "frames-jambs", label: "Frames & jambs" }, { slug: "storefront-curtain-wall", label: "Storefront & curtain wall" }, { slug: "interior-trim-casing", label: "Interior trim & casing" }] },
  { slug: "cabinets-countertops-fixtures", label: "Cabinets, Countertops & Fixtures", masterFormat: "Div 12", subcategories: [{ slug: "kitchen-cabinets", label: "Kitchen cabinets" }, { slug: "bath-vanities", label: "Bath vanities" }, { slug: "countertops", label: "Countertops (quartz, granite, solid surface, laminate)" }, { slug: "closet-storage-systems", label: "Closet & storage systems" }, { slug: "shelving", label: "Shelving" }, { slug: "mirrors-bath-accessories", label: "Mirrors & bath accessories" }, { slug: "commercial-casework", label: "Commercial casework" }] },
  { slug: "electrical-lighting", label: "Electrical & Lighting", masterFormat: "Div 26, 27, 28", subcategories: [{ slug: "wire-cable", label: "Wire & cable" }, { slug: "conduit-fittings", label: "Conduit & fittings" }, { slug: "boxes-enclosures", label: "Boxes & enclosures" }, { slug: "panels-load-centers", label: "Panels & load centers" }, { slug: "breakers", label: "Breakers" }, { slug: "switches-receptacles", label: "Switches & receptacles" }, { slug: "wiring-devices-plates", label: "Wiring devices & plates" }, { slug: "interior-lighting", label: "Interior lighting" }, { slug: "exterior-site-lighting", label: "Exterior & site lighting" }, { slug: "temporary-jobsite-lighting", label: "Temporary jobsite lighting" }, { slug: "transfer-switches", label: "Transfer switches" }, { slug: "low-voltage-data", label: "Low voltage & data" }, { slug: "fire-alarm-security", label: "Fire alarm & security" }, { slug: "solar-ev-charging", label: "Solar & EV charging" }] },
  { slug: "plumbing", label: "Plumbing", masterFormat: "Div 22", subcategories: [{ slug: "pipe-tubing", label: "Pipe & tubing (PVC, CPVC, PEX, copper)" }, { slug: "fittings-valves", label: "Fittings & valves" }, { slug: "drainage-dwv", label: "Drainage & DWV" }, { slug: "water-heaters", label: "Water heaters (tank & tankless)" }, { slug: "plumbing-fixtures", label: "Sinks, toilets, tubs & showers" }, { slug: "faucets-trim", label: "Faucets & trim" }, { slug: "plumbing-pumps", label: "Pumps (sump, well, booster)" }, { slug: "water-treatment", label: "Water treatment" }, { slug: "backflow-meters", label: "Backflow & meters" }, { slug: "gas-piping", label: "Gas piping" }, { slug: "pipe-insulation", label: "Pipe insulation" }] },
  { slug: "hvac-mechanical", label: "HVAC & Mechanical", masterFormat: "Div 23", subcategories: [{ slug: "furnaces", label: "Furnaces" }, { slug: "ac-heat-pumps", label: "Air conditioners & heat pumps" }, { slug: "mini-splits", label: "Mini-splits" }, { slug: "boilers-radiant-heat", label: "Boilers & radiant heat" }, { slug: "rooftop-units", label: "Rooftop units" }, { slug: "air-handlers-coils", label: "Air handlers & coils" }, { slug: "ductwork-fittings", label: "Ductwork & fittings" }, { slug: "registers-grilles-diffusers", label: "Registers, grilles & diffusers" }, { slug: "ventilation-exhaust-fans", label: "Ventilation & exhaust fans" }, { slug: "thermostats-controls", label: "Thermostats & controls" }, { slug: "filters-iaq", label: "Filters & indoor air quality" }, { slug: "refrigerant-line-sets", label: "Refrigerant & line sets" }] },
  { slug: "fasteners-hardware-connectors", label: "Fasteners, Hardware & Structural Connectors", masterFormat: "Div 05, 06 05 23", subcategories: [{ slug: "nails", label: "Nails" }, { slug: "screws", label: "Screws" }, { slug: "bolts-nuts-washers", label: "Bolts, nuts & washers" }, { slug: "anchors", label: "Concrete & masonry anchors" }, { slug: "structural-connectors", label: "Structural connectors (joist hangers, straps, hold-downs)" }, { slug: "threaded-rod", label: "Threaded rod" }, { slug: "rivets", label: "Rivets" }, { slug: "chain-rope-rigging", label: "Chain, rope & rigging hardware" }, { slug: "hinges-brackets", label: "Hinges & brackets" }] },
  { slug: "metals-steel", label: "Metals & Steel", masterFormat: "Div 05", subcategories: [{ slug: "structural-steel", label: "Structural steel (beams, columns)" }, { slug: "angle-channel-flat-bar", label: "Angle, channel & flat bar" }, { slug: "metal-decking", label: "Metal decking" }, { slug: "sheet-metal", label: "Sheet metal" }, { slug: "aluminum-extrusion", label: "Aluminum extrusion" }, { slug: "handrail-guardrail", label: "Handrail & guardrail" }, { slug: "stairs-ladders", label: "Fixed stairs & ladders" }, { slug: "expanded-perforated-metal", label: "Expanded & perforated metal" }, { slug: "welding-consumables", label: "Welding consumables" }] },
  { slug: "flooring-tile", label: "Flooring & Tile", masterFormat: "Div 09 60 00", subcategories: [{ slug: "hardwood", label: "Hardwood" }, { slug: "engineered-wood", label: "Engineered wood" }, { slug: "laminate", label: "Laminate" }, { slug: "vinyl-flooring", label: "Luxury vinyl (LVP/LVT) & sheet vinyl" }, { slug: "carpet", label: "Carpet & carpet tile" }, { slug: "ceramic-porcelain-tile", label: "Ceramic & porcelain tile" }, { slug: "natural-stone-tile", label: "Natural stone tile" }, { slug: "underlayment-subfloor", label: "Underlayment & subfloor" }, { slug: "thinset-grout-setting", label: "Thinset, grout & setting materials" }, { slug: "epoxy-resinous-flooring", label: "Epoxy & resinous flooring" }, { slug: "polished-sealed-concrete", label: "Polished & sealed concrete" }, { slug: "transitions-trim", label: "Transitions & trim" }] },
  { slug: "sitework-landscape-hardscape", label: "Sitework, Landscape & Hardscape", masterFormat: "Div 31, 32", subcategories: [{ slug: "aggregate-sand-gravel", label: "Aggregate, sand & gravel" }, { slug: "topsoil-fill", label: "Topsoil & fill" }, { slug: "erosion-control", label: "Erosion control (silt fence, blankets)" }, { slug: "geotextile-geogrid", label: "Geotextile & geogrid" }, { slug: "drainage-pipe-culvert", label: "Drainage pipe & culvert" }, { slug: "asphalt-paving-materials", label: "Asphalt & paving materials" }, { slug: "sealcoat-striping", label: "Sealcoat & striping" }, { slug: "fencing-gates", label: "Fencing & gates" }, { slug: "retaining-wall-systems", label: "Retaining wall systems" }, { slug: "sod-seed-plantings", label: "Sod, seed & plantings" }, { slug: "irrigation", label: "Irrigation" }, { slug: "mulch-decorative-stone", label: "Mulch & decorative stone" }] },
  { slug: "safety-ppe-jobsite", label: "Safety, PPE & Jobsite Supplies", masterFormat: "Div 01 50 00", subcategories: [{ slug: "head-eye-hearing-protection", label: "Hard hats, eye & hearing protection" }, { slug: "gloves", label: "Gloves" }, { slug: "hi-vis-workwear", label: "Hi-vis & workwear" }, { slug: "fall-protection", label: "Fall protection (harnesses, lanyards, anchors)" }, { slug: "respiratory-protection", label: "Respiratory protection" }, { slug: "traffic-control", label: "Traffic control (cones, barricades, signs)" }, { slug: "barricade-tape", label: "Caution & barricade tape" }, { slug: "first-aid", label: "First aid" }, { slug: "fire-extinguishers", label: "Fire extinguishers" }, { slug: "temporary-fencing-barriers", label: "Temporary fencing & barriers" }, { slug: "jobsite-cleanup", label: "Jobsite cleanup supplies" }] },
  { slug: "tools-accessories", label: "Tools & Tool Accessories (purchase)", masterFormat: "Div 01 54 00", subcategories: [{ slug: "hand-tools", label: "Hand tools" }, { slug: "power-tools", label: "Cordless & corded power tools" }, { slug: "pneumatic-tools", label: "Pneumatic tools" }, { slug: "blades-bits-abrasives", label: "Blades, bits & abrasives" }, { slug: "layout-measuring", label: "Layout & measuring (levels, lasers, tape)" }, { slug: "tool-storage", label: "Tool storage" }, { slug: "ladders-step-stools", label: "Ladders & step stools" }, { slug: "work-lights", label: "Work lights" }, { slug: "batteries-chargers", label: "Batteries & chargers" }] },
];

export const EQUIPMENT_CATEGORIES: TaxCategory[] = [
  { slug: "earthmoving-excavation", label: "Earthmoving & Excavation", subcategories: [{ slug: "excavators", label: "Excavators (mini & standard)" }, { slug: "backhoe-loaders", label: "Backhoe loaders" }, { slug: "dozers", label: "Dozers" }, { slug: "skid-steers-ctl", label: "Skid steers & compact track loaders" }, { slug: "wheel-loaders", label: "Wheel loaders" }, { slug: "motor-graders", label: "Motor graders" }, { slug: "trenchers", label: "Trenchers" }, { slug: "scrapers", label: "Scrapers" }, { slug: "earthmoving-attachments", label: "Attachments (buckets, breakers, augers, grapples)" }] },
  { slug: "compaction-paving", label: "Compaction & Paving", subcategories: [{ slug: "plate-compactors", label: "Plate compactors" }, { slug: "rammers", label: "Rammers (jumping jacks)" }, { slug: "walk-behind-rollers", label: "Walk-behind rollers" }, { slug: "ride-on-rollers", label: "Ride-on rollers" }, { slug: "asphalt-pavers", label: "Asphalt pavers" }, { slug: "milling-machines", label: "Milling machines" }, { slug: "asphalt-distributors", label: "Asphalt distributors" }, { slug: "concrete-asphalt-saws", label: "Concrete & asphalt saws" }, { slug: "sealcoating-striping", label: "Sealcoating & line striping equipment" }] },
  { slug: "aerial-lifts-access", label: "Aerial Lifts & Access", subcategories: [{ slug: "scissor-lifts", label: "Scissor lifts (electric & rough terrain)" }, { slug: "articulating-boom-lifts", label: "Articulating boom lifts" }, { slug: "telescopic-boom-lifts", label: "Telescopic boom lifts" }, { slug: "towable-boom-lifts", label: "Towable boom lifts" }, { slug: "mast-lifts", label: "Personnel & vertical mast lifts" }, { slug: "telehandlers", label: "Telehandlers" }, { slug: "material-lifts-hoists", label: "Material lifts & hoists" }] },
  { slug: "cranes-hoists-rigging", label: "Cranes, Hoists & Rigging", subcategories: [{ slug: "mobile-truck-cranes", label: "Mobile & truck cranes" }, { slug: "rough-terrain-cranes", label: "Rough-terrain cranes" }, { slug: "tower-cranes", label: "Tower cranes" }, { slug: "carry-deck-cranes", label: "Carry-deck cranes" }, { slug: "boom-trucks", label: "Boom trucks" }, { slug: "hoists-winches", label: "Hoists & winches" }, { slug: "gantry-cranes", label: "Gantry cranes" }, { slug: "rigging-slings", label: "Rigging, slings & spreader bars" }] },
  { slug: "concrete-masonry-equipment", label: "Concrete & Masonry Equipment", subcategories: [{ slug: "concrete-mixers", label: "Concrete mixers" }, { slug: "concrete-pumps", label: "Concrete pumps & placing booms" }, { slug: "power-trowels", label: "Power trowels" }, { slug: "screeds", label: "Screeds" }, { slug: "concrete-vibrators", label: "Concrete vibrators" }, { slug: "core-drills", label: "Core drills" }, { slug: "grinders-polishers", label: "Concrete grinders & polishers" }, { slug: "scarifiers-shot-blasters", label: "Scarifiers & shot blasters" }, { slug: "masonry-saws", label: "Masonry saws" }, { slug: "mortar-mixers", label: "Mortar mixers" }, { slug: "concrete-buggies", label: "Concrete buggies" }] },
  { slug: "power-air-welding", label: "Power, Air & Welding", subcategories: [{ slug: "portable-air-compressors", label: "Portable air compressors" }, { slug: "towable-air-compressors", label: "Towable air compressors" }, { slug: "portable-generators", label: "Portable generators" }, { slug: "towable-standby-generators", label: "Towable & standby generators" }, { slug: "light-towers", label: "Light towers" }, { slug: "engine-driven-welders", label: "Engine-driven welders" }, { slug: "welding-machines", label: "Welding machines" }, { slug: "power-distribution", label: "Power distribution & spider boxes" }, { slug: "cable-cords", label: "Cable & cords" }, { slug: "battery-energy-storage", label: "Battery energy storage" }] },
  { slug: "material-handling-forklifts", label: "Material Handling & Forklifts", subcategories: [{ slug: "warehouse-forklifts", label: "Warehouse forklifts" }, { slug: "rough-terrain-forklifts", label: "Rough-terrain forklifts" }, { slug: "pallet-jacks", label: "Pallet jacks" }, { slug: "conveyors", label: "Conveyors" }, { slug: "dollies-carts-wheelbarrows", label: "Dollies, carts & wheelbarrows" }, { slug: "drum-cylinder-handling", label: "Drum & cylinder handling" }, { slug: "cable-pullers", label: "Cable pullers" }] },
  { slug: "trucks-trailers", label: "Trucks & Trailers", subcategories: [{ slug: "dump-trucks", label: "Dump trucks" }, { slug: "flatbed-stake-trucks", label: "Flatbed & stake trucks" }, { slug: "service-mechanic-trucks", label: "Service & mechanic trucks" }, { slug: "water-trucks", label: "Water trucks" }, { slug: "bucket-boom-trucks", label: "Bucket & boom trucks" }, { slug: "vacuum-sweeper-trucks", label: "Vacuum & sweeper trucks" }, { slug: "utility-trailers", label: "Utility trailers" }, { slug: "equipment-lowboy-trailers", label: "Equipment & lowboy trailers" }, { slug: "dump-trailers", label: "Dump trailers" }] },
  { slug: "pumps-water-dewatering", label: "Pumps, Water & Dewatering", subcategories: [{ slug: "trash-pumps", label: "Trash pumps" }, { slug: "submersible-pumps", label: "Submersible pumps" }, { slug: "diaphragm-pumps", label: "Diaphragm pumps" }, { slug: "wellpoint-dewatering", label: "Wellpoint & dewatering systems" }, { slug: "hoses-fittings", label: "Hoses & fittings" }, { slug: "water-tanks", label: "Water tanks" }, { slug: "pressure-washers", label: "Pressure washers" }] },
  { slug: "climate-control-air-quality", label: "Climate Control & Air Quality", subcategories: [{ slug: "heaters", label: "Indirect & direct-fired heaters" }, { slug: "portable-ac-spot-coolers", label: "Portable AC & spot coolers" }, { slug: "dehumidifiers", label: "Dehumidifiers" }, { slug: "air-movers-blowers", label: "Air movers & blowers" }, { slug: "air-scrubbers", label: "Air scrubbers & negative air machines" }, { slug: "ventilation-fans", label: "Ventilation fans" }, { slug: "containment-abatement", label: "Containment & abatement equipment" }] },
  { slug: "demolition-specialty", label: "Demolition & Specialty Trade Equipment", subcategories: [{ slug: "demolition-hammers-breakers", label: "Demolition hammers & breakers" }, { slug: "rotary-core-drills", label: "Rotary & core drills" }, { slug: "concrete-wall-wire-saws", label: "Concrete, wall & wire saws" }, { slug: "chain-saws", label: "Chain saws" }, { slug: "drain-cleaning-jetting", label: "Drain cleaning & jetting" }, { slug: "pipe-threading-fusion", label: "Pipe threading & fusion" }, { slug: "hvac-service-recovery", label: "HVAC service & recovery tools" }, { slug: "insulation-blowers", label: "Insulation blowers" }, { slug: "floor-prep-surface-removal", label: "Floor prep & surface removal" }, { slug: "sanders-dust-extraction", label: "Sanders & dust extraction" }] },
  { slug: "surveying-detection-inspection", label: "Surveying, Detection & Inspection", subcategories: [{ slug: "total-stations-gps", label: "Total stations & GPS rovers" }, { slug: "laser-rotary-levels", label: "Laser & rotary levels" }, { slug: "machine-control", label: "Machine control" }, { slug: "utility-cable-locators", label: "Utility & cable locators" }, { slug: "pipe-inspection-cameras", label: "Sewer & pipe inspection cameras" }, { slug: "concrete-scanners-gpr", label: "Concrete scanners (GPR)" }, { slug: "thermal-imaging", label: "Thermal imaging" }, { slug: "moisture-meters", label: "Moisture meters" }, { slug: "gas-detection-monitors", label: "Gas detection & confined-space monitors" }] },
  { slug: "landscaping-grounds", label: "Landscaping & Grounds Equipment", subcategories: [{ slug: "stump-grinders", label: "Stump grinders" }, { slug: "chippers", label: "Chippers" }, { slug: "chainsaws-pole-saws", label: "Chainsaws & pole saws" }, { slug: "mowers-brush-cutters", label: "Mowers & brush cutters" }, { slug: "tillers-augers", label: "Tillers & augers" }, { slug: "sod-cutters", label: "Sod cutters" }, { slug: "aerators-seeders", label: "Aerators & seeders" }, { slug: "landscape-blowers", label: "Blowers" }, { slug: "log-splitters", label: "Log splitters" }] },
  { slug: "scaffolding-shoring-site-support", label: "Scaffolding, Shoring & Site Support", subcategories: [{ slug: "frame-system-scaffolding", label: "Frame & system scaffolding" }, { slug: "mobile-scaffold-towers", label: "Mobile scaffold towers" }, { slug: "shoring-jacks", label: "Shoring & jacks" }, { slug: "trench-boxes", label: "Trench boxes & shoring" }, { slug: "job-boxes-containers", label: "Job boxes & storage containers" }, { slug: "portable-offices-trailers", label: "Portable offices & trailers" }, { slug: "portable-toilets-wash", label: "Portable toilets & wash stations" }, { slug: "temporary-fencing", label: "Temporary fencing" }, { slug: "barricades", label: "Barricades" }] },
  { slug: "cleaning-waste-equipment", label: "Cleaning & Waste Equipment", subcategories: [{ slug: "floor-scrubbers-sweepers", label: "Floor scrubbers & sweepers" }, { slug: "hepa-wet-dry-vacuums", label: "HEPA & wet/dry vacuums" }, { slug: "dumpsters-roll-offs", label: "Dumpsters & roll-offs" }, { slug: "compactors-balers", label: "Compactors & balers" }, { slug: "spill-containment", label: "Spill containment" }, { slug: "sweeper-attachments", label: "Sweeper attachments" }] },
];

export function categoriesFor(kind: ItemKind): TaxCategory[] {
  return kind === "product" ? PRODUCT_CATEGORIES : EQUIPMENT_CATEGORIES;
}

export function findCategory(kind: ItemKind, slug: string): TaxCategory | undefined {
  return categoriesFor(kind).find((c) => c.slug === slug);
}

export function findSubcategory(
  kind: ItemKind,
  categorySlug: string,
  subSlug: string,
): TaxSubcategory | undefined {
  return findCategory(kind, categorySlug)?.subcategories.find((s) => s.slug === subSlug);
}

export function isValidCategory(kind: ItemKind, slug: string): boolean {
  return !!findCategory(kind, slug);
}

export function isValidSubcategory(
  kind: ItemKind,
  categorySlug: string,
  subSlug: string,
): boolean {
  return !!findSubcategory(kind, categorySlug, subSlug);
}

/** Human label for a category slug, searching the given kind (or both). */
export function categoryLabel(slug: string, kind?: ItemKind): string | null {
  const pools = kind ? [categoriesFor(kind)] : [PRODUCT_CATEGORIES, EQUIPMENT_CATEGORIES];
  for (const pool of pools) {
    const hit = pool.find((c) => c.slug === slug);
    if (hit) return hit.label;
  }
  return null;
}

/** Human label for a sub-category slug within a category. */
export function subcategoryLabel(
  categorySlug: string,
  subSlug: string,
  kind?: ItemKind,
): string | null {
  const kinds: ItemKind[] = kind ? [kind] : ["product", "equipment"];
  for (const k of kinds) {
    const hit = findSubcategory(k, categorySlug, subSlug);
    if (hit) return hit.label;
  }
  return null;
}

/** Which kind owns this category slug (product/equipment), or null. */
export function kindOfCategory(slug: string): ItemKind | null {
  if (PRODUCT_CATEGORIES.some((c) => c.slug === slug)) return "product";
  if (EQUIPMENT_CATEGORIES.some((c) => c.slug === slug)) return "equipment";
  return null;
}
